#!/usr/bin/env python3
"""Create deterministic development, validation, and held-out query files."""

import argparse
import hashlib
import json
import random
import sys
from pathlib import Path


def load_rows(path):
    header = "query_id|query|judgments"
    rows = []
    seen = set()
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        value = line.strip()
        if not value or value.startswith("#"):
            continue
        if value == header:
            continue
        fields = value.split("|", 2)
        if len(fields) != 3 or not all(fields):
            raise ValueError(f"line {number}: expected query_id|query|judgments")
        if fields[0] in seen:
            raise ValueError(f"duplicate query_id: {fields[0]}")
        seen.add(fields[0])
        rows.append((fields[0], value))
    if len(rows) < 3:
        raise ValueError("at least three queries are required")
    return rows


def assignments(rows, seed, train_fraction, validation_fraction):
    if not 0.0 < train_fraction < 1.0 or not 0.0 < validation_fraction < 1.0:
        raise ValueError("fractions must be between zero and one")
    if train_fraction + validation_fraction >= 1.0:
        raise ValueError("train and validation fractions must leave a test split")
    shuffled = list(rows)
    random.Random(seed).shuffle(shuffled)
    train_count = max(1, round(len(rows) * train_fraction))
    validation_count = max(1, round(len(rows) * validation_fraction))
    if train_count + validation_count >= len(rows):
        validation_count = len(rows) - train_count - 1
    result = {}
    for query_id, _row in shuffled[:train_count]:
        result[query_id] = "development"
    for query_id, _row in shuffled[train_count:train_count + validation_count]:
        result[query_id] = "validation"
    for query_id, _row in shuffled[train_count + validation_count:]:
        result[query_id] = "test"
    return result


def write_split(path, rows, assignment, split):
    selected = [row for row in rows if assignment[row[0]] == split]
    path.write_text(
        f"# query split generated by tools/split_query_set.py\n# split={split}\nquery_id|query|judgments\n"
        + "\n".join(row for _query_id, row in selected) + "\n", encoding="utf-8")
    return selected


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--queries", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--corpus-version", required=True)
    parser.add_argument("--code-revision", required=True)
    parser.add_argument("--train-fraction", type=float, default=0.60)
    parser.add_argument("--validation-fraction", type=float, default=0.20)
    args = parser.parse_args()
    try:
        rows = load_rows(args.queries)
        assignment = assignments(rows, args.seed, args.train_fraction, args.validation_fraction)
        args.output_dir.mkdir(parents=True, exist_ok=True)
        counts = {}
        for split in ("development", "validation", "test"):
            selected = write_split(args.output_dir / f"queries-{split}.psv", rows, assignment, split)
            counts[split] = len(selected)
        source_hash = hashlib.sha256(args.queries.read_bytes()).hexdigest()
        manifest = {
            "schemaVersion": "query-split-manifest-v1",
            "sourceQueries": str(args.queries),
            "sourceSha256": source_hash,
            "seed": args.seed,
            "fractions": {"development": args.train_fraction, "validation": args.validation_fraction,
                           "test": 1.0 - args.train_fraction - args.validation_fraction},
            "corpusVersion": args.corpus_version,
            "codeRevision": args.code_revision,
            "counts": counts,
            "assignments": dict(sorted(assignment.items())),
        }
        (args.output_dir / "split-manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        print(json.dumps({"status": "created", "counts": counts}, sort_keys=True))
        return 0
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
